SusDulu/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SusDulu.Models
{
    public class Payment
    {
        [Required]
        public string Email { get; set; }
        public string Name { get; set; }
        public string CreditCardNum { get; set; }
    }
}

SusDulu/Controllers/PaymentController.cs
using SusDulu.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using RazorPDF;

namespace SusDulu.Controllers
{
    public class PaymentController : Controller
    {
        private DefaultConnection db = new DefaultConnection();

        //
        // GET: /Payment/

        public ActionResult Index()
        {
            if (TempData["idFlight1"] == null)
            {
                ViewBag.Error = true;
            }
            else
            {
                ViewBag.Error = false;
                List<string> emailL = (List<string>)TempData["email"];
                List<string> firstL = (List<string>)TempData["first"];
                List<string> middleL = (List<string>)TempData["middle"];
                List<string> lastL = (List<string>)TempData["last"];
                List<string> addressL = (List<string>)TempData["address"];
                List<string> phoneL = (List<string>)TempData["phone"];
                List<string> genderL = (List<string>)TempData["gender"];
                List<string> cityL = (List<string>)TempData["city"];
                List<string> provinceL = (List<string>)TempData["province"];
                List<string> postcodeL = (List<string>)TempData["postcode"];
                List<string> classL = (List<string>)TempData["class"];
                List<int> priceL = (List<int>)TempData["price"];
                List<string> seatL = (List<string>)TempData["seat"];

                int id_flight1 = int.Parse(TempData["idFlight1"].ToString());
                int id_flight2 = int.Parse(TempData["idFlight2"].ToString());
                int sum = int.Parse(TempData["sum"].ToString());
                if (id_flight2 != 0)
                {
                    sum *= 2;
                }

                //generate ID Ticket auto-increment
                List<int> tickIDList = new List<int>();
                var tickIDQry = from t in db.Tickets
                                select t.ID;
                tickIDList.AddRange(tickIDQry.Distinct());
                int lastElmt;
                try
                {
                    lastElmt = tickIDList.Last();
                }
                catch (InvalidOperationException e)
                {
                    lastElmt = 0;
                }
                int newID = lastElmt + 1;

                int? IDUser = WebSecurity.CurrentUserId;
                if (IDUser < 0) IDUser = null;

                Debug.WriteLine("IDUSER: " + IDUser);

                var tickets = new List<Ticket>();

                for (int k = 0; k < emailL.Count; k++)
                {
                    if (ModelState.IsValid)
                    {
                        //get certain IDUser
                        List<int> userIDList = new List<int>();

                        Ticket departureTicket = new Ticket()
                        {
                            ID_user = IDUser,
                            ID_flight = id_flight1,
                            Email = emailL[k],
                            First_name = firstL[k],
                            Middle_name = middleL[k],
                            Last_name = lastL[k],
                            Address = addressL[k],
                            Phone = phoneL[k],
                            Gender = genderL[k],
                            City = cityL[k],
                            Province = provinceL[k],
                            Postcode = postcodeL[k],
                            Class = classL[k],
                            Price = priceL[k],
                            Seat = seatL[k]
                        };

                        db.Tickets.Add(departureTicket);
                        tickets.Add(departureTicket);

                        if (id_flight2 != 0)
                        {
                            Ticket returnTicket = new Ticket()
                            {
                                ID_user = IDUser,
                                ID_flight = id_flight2,
                                Email = emailL[k],
                                First_name = firstL[k],
                                Middle_name = middleL[k],
                                Last_name = lastL[k],
                                Address = addressL[k],
                                Phone = phoneL[k],
                                Gender = genderL[k],
                                City = cityL[k],
                                Province = provinceL[k],
                                Postcode = postcodeL[k],
                                Class = classL[k],
                                Price = priceL[k],
                                Seat = seatL[k]
                            };

                            db.Tickets.Add(returnTicket);
                            tickets.Add(returnTicket);
                        }
                    }
                }

                db.SaveChanges();

                ViewBag.sum = sum;
                ViewBag.firstID = newID;
                ViewBag.tickets = tickets;
            }
            
            return View();
        }

        [AllowAnonymous]
        public ActionResult Print(int idTiket)
        {
            Ticket tiket = db.Tickets.Find(idTiket);
            if (tiket == null)
            {
                return HttpNotFound();
            }

            var pdfresult = new PdfResult(tiket, "Print");
            return pdfresult;

        }
    }
}

SusDulu/Views/Payment/Index.cshtml
@{
    ViewBag.Title = "Pencetakan Tiket";
}

@if (ViewBag.Error)
{
<h1 class="page-header">Pembayaran Gagal</h1>
<p class="lead">Mohon maaf, pemesanan Anda gagal kami proses. Silakan mengulang kembali pesanan Anda.</p>
<a href="@Url.Action("Index", "Home")" class="btn btn-lg btn-danger">Kembali ke beranda</a>
}
else
{
<h1 class="page-header">Pembayaran Berhasil</h1>

<p class="lead">Pembayaran Anda telah kami terima. Silakan cetak tiket Anda di bawah ini. Terima kasih telah menggunakan jasa Erlangga Airlines.</p>

<h3>Cetak Tiket Anda</h3>

<table class="table">
    <tr>
        <th></th>
        <th colspan="2">Keberangkatan</th>
        <th colspan="2">Kedatangan</th>
        <th>Nama Penumpang</th>
        <th>Kelas</th>
        <th>Kursi</th>
        <th></th>
    </tr>
    @foreach (SusDulu.Models.Ticket t in ViewBag.tickets)
    {
    <tr>
        @{
            SusDulu.Models.Flight flight = t.GetFlight();
            var flightNo = (flight != null) ? flight.Flight_number : "";
            var origin = (flight != null) ? flight.GetOriginAirport() : new SusDulu.Models.Airport();
            var destination = (flight != null) ? flight.GetDestinationAirport() : new SusDulu.Models.Airport();
        }
        <td><i class="glyphicon glyphicon-plane"></i>&nbsp;@flightNo</td>
        <td>@origin.Name (@origin.ID)</td>
        <td><i class="glyphicon glyphicon-calendar"></i>&nbsp;@flight.GetDepartureDateTime().ToShortDateString() &nbsp; <i class="glyphicon glyphicon-time"></i>&nbsp; @flight.Departure_time</td>
        <td>@destination.Name (@destination.ID)</td>
        <td><i class="glyphicon glyphicon-calendar"></i>&nbsp;@flight.GetArrivalDateTime().ToShortDateString() &nbsp; <i class="glyphicon glyphicon-time"></i>&nbsp; @flight.Arrival_time</td>
        <td>@t.GetFullName()</td>
        <td>@(t.Class == "FIRSTCLASS" ? "Eksekutif" : (t.Class == "BUSINESS" ? "Bisnis" : "Ekonomi"))</td>
        <td>@t.Seat</td>
        <td>
            <a href="@Url.Action("Print", new { idTiket = t.ID })" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-print"></i>&nbsp;Cetak Tiket</a>
        </td>
    </tr>
    }
</table>
}


@*@using (Html.BeginForm("Index", "Home", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    
    int IDFirst = ViewBag.firstID;
    int IDLast = IDFirst - 1 + ViewBag.sum;
    for (int i = IDFirst, j = 1; i <= IDLast; i++, j++)
    {
        <h4>
        @Html.ActionLink("Tiket " + j, "Print", "Payment", new { idTiket = i }, new { idTiket = i })
        </h4>
    }

}*@

SusDulu/Views/Payment/Print.cshtml
@model SusDulu.Models.Ticket
@{
    ViewBag.Title = "Cetak Tiket";
    Layout = null;
}

<itext producer="RazorPDF">
    <table width="100%" cellpadding="0.5" cellspacing="0.5" widths="30;70" borderwidth="1.0" left="false" right="false" top="false" bottom="false" red="0" green="0" blue="0">
        <row>
            <cell>
                <chunk style="font-weight:bold;">ID:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.ID</chunk>
            </cell>
        </row>
        <row>
            <cell>
                <chunk style="font-weight:bold;">ID Flight:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.ID_flight</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Email:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Email</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">First Name:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.First_name</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Middle Name:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Middle_name</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Last Name:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Last_name</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Address:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Address</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Phone:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Phone</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Gender:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Gender</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">City:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.City</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Province:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Province</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Postcode:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Postcode</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Class:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Class</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Price:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Price</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Seat:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.Seat</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Flight Number:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.getPenerbangan().Flight_number</chunk>
            </cell>
        </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Departure:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.getPenerbangan().Departure_date , @Model.getPenerbangan().Departure_time </chunk>
                </cell>
            </row>
        <row>
            <cell>
                <chunk style="font-weight:bold;">Arrival:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.getPenerbangan().Arrival_date , @Model.getPenerbangan().Arrival_time </chunk>
                </cell>
            </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Origin:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.getPenerbangan().Origin</chunk>
                </cell>
            </row>

        <row>
            <cell>
                <chunk style="font-weight:bold;">Destination:</chunk>
            </cell>
            <cell>
                <chunk style="">@Model.getPenerbangan().Destination</chunk>
                </cell>
            </row>

       

    </table>
</itext>