SusDulu/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SusDulu.Models;

namespace SusDulu.Controllers
{
    public class MemberController : Controller
    {
        private MembersContext db = new MembersContext();

        //
        // GET: /Member/

        public ActionResult Index()
        {
            return View(db.Members.ToList());
        }

        //
        // GET: /Member/Details/5

        public ActionResult Details(int id = 0)
        {
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        //
        // GET: /Member/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Member/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        //
        // GET: /Member/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        //
        // POST: /Member/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        //
        // GET: /Member/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        //
        // POST: /Member/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SusDulu/Views/Member/Create.cshtml
@model SusDulu.Models.Member

@{
    ViewBag.Title = "Create";
}

<h1 class="page-header">Pendaftaran Anggota</h1>
<div class="row">
    <div class="col-sm-4 reg-intro">
        <p class="lead">Untuk memanfaatkan fitur-fitur online Airlangga Airlines, silakan mendaftar terlebih dahulu di laman ini.</p>
        <p>Dengan mendaftar, Anda dapat:</p>
        <ul>
            <li>Memesan tiket secara online</li>
            <li>Melakukan online check-in</li>
            <li>dst.</li>
        </ul>
    </div>
    <div class="col-sm-8">
@using (Html.BeginForm("Create", "Member", FormMethod.Post, new { @class = "form-horizontal reg-form" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
            <fieldset>
                <legend>Formulir Pendaftaran</legend>
                <div class="form-group">
                    <label class="control-label col-lg-3">Username</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="text" name="username">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Password</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="password" name="password">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Ulangi Password</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="password" name="confirm_password">
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>Informasi Pribadi</legend>
                <div class="form-group">
                    <label class="control-label col-lg-3">Jenis Kelamin</label>
                    <div class="col-lg-9">
                        <select name="sex" class="form-control">
                            <option value="F">Perempuan</option>
                            <option value="M">Laki-laki</option>
                        </select>
                    </div>
                </div>
                @*<div class="form-group">
                    <label class="control-label col-lg-3">Tanggal Lahir</label>
                    <div class="col-lg-9">
                        <select name="dob_d" class="input-mini">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                            <option>9</option>
                            <option>10</option>
                            <option>11</option>
                            <option>12</option>
                            <option>13</option>
                            <option>14</option>
                            <option>15</option>
                            <option>16</option>
                            <option>17</option>
                            <option>18</option>
                            <option>19</option>
                            <option>20</option>
                            <option>21</option>
                            <option>22</option>
                            <option>23</option>
                            <option>24</option>
                            <option>25</option>
                            <option>26</option>
                            <option>27</option>
                            <option>28</option>
                            <option>29</option>
                            <option>30</option>
                            <option>31</option>
                        </select>
                        <select name="dob_m" class="input-medium">
                            <option value="1">Januari</option>
                            <option value="2">Februari</option>
                            <option value="3">Maret</option>
                            <option value="4">April</option>
                            <option value="5">Mei</option>
                            <option value="6">Juni</option>
                            <option value="7">Juli</option>
                            <option value="8">Agustus</option>
                            <option value="9">September</option>
                            <option value="10">Oktober</option>
                            <option value="11">November</option>
                            <option value="12">Desember</option>
                        </select>
                        <select name="dob_y" class="input-small">
                            <option>1996</option>
                            <option>1995</option>
                            <option>1994</option>
                            <option>1993</option>
                            <option>1992</option>
                            <option>1991</option>
                            <option>1990</option>
                            <option>1989</option>
                            <option>1988</option>
                            <option>1987</option>
                            <option>1986</option>
                            <option>1985</option>
                            <option>1984</option>
                            <option>1983</option>
                            <option>1982</option>
                            <option>1981</option>
                            <option>1980</option>
                            <option>1979</option>
                            <option>1978</option>
                            <option>1977</option>
                            <option>1976</option>
                            <option>1975</option>
                            <option>1974</option>
                            <option>1973</option>
                            <option>1972</option>
                            <option>1971</option>
                            <option>1970</option>
                            <option>1969</option>
                            <option>1968</option>
                            <option>1967</option>
                            <option>1966</option>
                            <option>1965</option>
                            <option>1964</option>
                            <option>1963</option>
                            <option>1962</option>
                            <option>1961</option>
                            <option>1960</option>
                            <option>1959</option>
                            <option>1958</option>
                            <option>1957</option>
                            <option>1956</option>
                            <option>1955</option>
                            <option>1954</option>
                            <option>1953</option>
                            <option>1952</option>
                            <option>1951</option>
                            <option>1950</option>
                            <option>1949</option>
                            <option>1948</option>
                            <option>1947</option>
                            <option>1946</option>
                            <option>1945</option>
                            <option>1944</option>
                            <option>1943</option>
                            <option>1942</option>
                            <option>1941</option>
                            <option>1940</option>
                            <option>1939</option>
                            <option>1938</option>
                            <option>1937</option>
                            <option>1936</option>
                            <option>1935</option>
                            <option>1934</option>
                            <option>1933</option>
                            <option>1932</option>
                            <option>1931</option>
                            <option>1930</option>
                            <option>1929</option>
                            <option>1928</option>
                            <option>1927</option>
                            <option>1926</option>
                            <option>1925</option>
                            <option>1924</option>
                            <option>1923</option>
                            <option>1922</option>
                            <option>1921</option>
                            <option>1920</option>
                            <option>1919</option>
                            <option>1918</option>
                            <option>1917</option>
                            <option>1916</option>
                            <option>1915</option>
                            <option>1914</option>
                            <option>1913</option>
                            <option>1912</option>
                            <option>1911</option>
                            <option>1910</option>
                            <option>1909</option>
                            <option>1908</option>
                            <option>1907</option>
                            <option>1906</option>
                            <option>1905</option>
                            <option>1904</option>
                            <option>1903</option>
                            <option>1902</option>
                            <option>1901</option>
                            <option>1900</option>
                        </select>
                    </div>
                </div>*@
                <div class="form-group">
                    <label class="control-label col-lg-3">Alamat Surel</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="email" name="email">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Alamat Rumah</label>
                    <div class="col-lg-9">
                        <textarea name="address" class="form-control"></textarea>
                    </div>
                </div>
                <!--
                <div class="form-group">
                    <label class="control-label col-lg-3">Kota</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="text" name="city">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-3">Provinsi</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="text" name="city">
                    </div>
                </div>
                -->
                <div class="form-group">
                    <label class="control-label col-lg-3">Nomor Telepon</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="tel" name="phone">
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                <div class="col-lg-offset-3 col-lg-9">
                    <button class="btn btn-primary" type="submit">Daftar</button>
                </div>
            </div>

}
    </div>
</div>

@*

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Member</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Distance_Traveled)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Distance_Traveled)
            @Html.ValidationMessageFor(model => model.Distance_Traveled)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
*@

SusDulu/Views/Member/Register.cshtml
@{
    ViewBag.Title = "Daftar";
}
<h1 class="page-header">Pendaftaran Anggota</h1>
<div class="row">
    <div class="span4 reg-intro">
        <p class="lead">Untuk memanfaatkan fitur-fitur online Airlangga Airlines, silakan mendaftar terlebih dahulu di laman ini.</p>
        <p>Dengan mendaftar, Anda dapat:</p>
        <ul>
            <li>Memesan tiket secara online</li>
            <li>Melakukan online check-in</li>
            <li>dst.</li>
        </ul>
    </div>
    <div class="span8">
        @using (Html.BeginForm("Register", "Member", FormMethod.Post, new { @class = "form-horizontal reg-form" })) 
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Formulir Pendaftaran</legend>
                <div class="control-group">
                    <label class="control-label">Email</label>
                    <div class="controls">
                        <input type="text" name="email">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Password</label>
                    <div class="controls">
                        <input type="password" name="password">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Ulangi Password</label>
                    <div class="controls">
                        <input type="password" name="confirm_password">
                    </div>
                </div>
                <input type="hidden" name="distance_traveled" value="0">
            </fieldset>

            <fieldset>
                <legend>Informasi Pribadi</legend>
                <div class="control-group">
                    <label class="control-label">Nama</label>
                    <div class="controls">
                        <input type="text" name="name">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Alamat Rumah</label>
                    <div class="controls">
                        <textarea name="address"></textarea>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Nomor Telepon</label>
                    <div class="controls">
                        <input type="tel" name="phone">
                    </div>
                </div>
            </fieldset>
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">Daftar</button>
            </div>
        }
    </div>
</div>